apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-config
  namespace: aegis
data:
  REDIS_URL: "redis://aegis-redis:6379/0"
  RABBITMQ_URL: "amqp://guest:guest@aegis-rabbitmq:5672/"
  POSTGRES_DB: "aegis_db"
  POSTGRES_USER: "aegis_admin"
  PAIRS: "BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,DOGEUSDT"
