apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-redis
  namespace: aegis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aegis-redis
  template:
    metadata:
      labels:
        app: aegis-redis
    spec:
      containers:
        - name: aegis-redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: redisdata
              mountPath: /data
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]          
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]          
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: aegis-redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aegis-redis-pvc
  namespace: aegis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
