"""Initial schema: Users, Portfolios, Transactions

Revision ID: 0b6ee466fb55
Revises: 8ce016c9a318
Create Date: 2026-04-06 17:10:19.770649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6ee466fb55'
down_revision: Union[str, None] = '8ce016c9a318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'transactions',
        'typre',
        new_column_name='type',
        existing_type=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'transactions',
        'type',
        new_column_name='typre',
        existing_type=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
